locals {
  timerand = formatdate("YYYYMMDD-hhmmss", timestamp())
}
 
resource "vra_deployment" "sg" {
  name = "DEPLOY_SG--${local.timerand}" #you should change this name after creation to prevent an update (use the tfstate name)
  description = "Generated by Terraform"
 
  catalog_item_id      = "id_du_catalog_id_sg"
  project_id           = "id_du_projet_sur_lequel_creer_la_machine"
 
  # Disparition de la cloud_zone et du basicat, qui ne sont plus nécessaires
  inputs = {
      additional_sg_name = "test-tf"
      description = "test"
  }
}
 
resource "vra_deployment" "vm" {
  name        = "nom-du-dep-${local.timerand}" #you should change this name after creation to prevent an update (use the tfstate name)
  description = "Generated by Terraform"
 
  catalog_item_id      = "id_du_catalog_id_rhel"
  project_id           = "id_du_projet_sur_lequel_creer_la_machine"
 
  inputs = {
    project_env = "horsprod"
    project_application_id = "30250"
    project_basicat = "is2"
    project_storage = "standard"
    application_module_26e = "BRMC IAAS NG - DEV - DIF"
    instance_role = "ws00"
    custom_instance_role = "" # 4 caractères si instance_role='cust'
    instance_count = 1
    instance_os = "RedHat8.6"
    instance_env = "dv"      # Généré depuis instance_usage dans le formulaire
    flavor_value = "g1"
    service_class = "standard"
    storage_class_tag = "standard"
    disk_size_1 = 20
    disk_size_2 = 10
    disk_size_3 = 0
    disk_size_4 = 0
    disk_size_5 = 0
    disk_size_6 = 0
    name_sg = "SG_AIP_ND1_ZIS_GRP_PP_IS20a_V4--is2_testdemo_00014"    # SG présente dans le projet
    root_password = "VMware1!VMware1!"
    osadmin_password = "VMware1!VMware1!"
    ode_ssh_key = ""
    operation_entity = "/Orange/Of/Dtsi/Pfc/Mosaic/Vic/Cops/"
    support_entity = "/Orange/Of/Dtsi/Pfc/Mosaic/Vic/Cops/"
    lease_day = "2023-01-08" #YYYY-MM-DD
  }
}